spring:
  profiles:
    active: server
    group:
      local:
        - db-local
      server:
        - db-server
    include:
      - key
      - db

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 100
    database-platform: org.hibernate.dialect.MariaDBDialect

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    display-request-duration: true

logging:
  level:
    com.app: DEBUG
    com.jpa: DEBUG
    org.springframework.jdbc.core: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE